version: "3.7"

services:
  postgres:
    image: postgres:9.6-alpine
  app:
    environment:
      PGUSER: postgres
      PGPORT: 5432
      PGHOST: postgres
    build:
      context: .
    ports:
      - "4000:4000"
    depends_on:
      - postgres
